spring:
  application:
    name: USER-SERVICE

server:
  port: 8082
  servlet:
    context-path: /api/user-service/


# Security configuration
security:
  jwt:
    token:
      secret-key: moneytransfersystem
